### ISSUE TITLE
Won't compile OSX 10.10.2 node 0.12.0

### ISSUE THREAD

**Issue by jimmyhmiller** [RayKitajima/pg-sync#6]
\
> pg-sync@0.1.3 install /usr/local/lib/node_modules/pg-sync
> node-gyp rebuild || (exit 0)

child_process: customFds option is deprecated, use stdio instead.
  CXX(target) Release/obj.target/pgsync/src/pgsync.o
  CXX(target) Release/obj.target/pgsync/src/connection.o
../src/connection.cc:140:28: error: no member named 'New' in 'v8::String'; did you mean simply 'New'?
        Handle<String> response = String::New(safeStr);
                                  ^~~~~~~~~~~
                                  New
../src/connection.cc:83:24: note: 'New' declared here
NAN_METHOD(Connection::New)
                       ^
../node_modules/nan/nan.h:1628:50: note: expanded from macro 'NAN_METHOD'
#define NAN_METHOD(name) _NAN_METHOD_RETURN_TYPE name(_NAN_METHOD_ARGS)
                                                 ^
../src/connection.cc:140:40: error: reference to type 'const v8::FunctionCallbackInfo<v8::Value>' could not bind to an lvalue of type 'char *'
        Handle<String> response = String::New(safeStr);
                                              ^~~~~~~
../src/connection.cc:83:1: note: passing argument to parameter 'args' here
NAN_METHOD(Connection::New)
^
../node_modules/nan/nan.h:1628:55: note: expanded from macro 'NAN_METHOD'
#define NAN_METHOD(name) _NAN_METHOD_RETURN_TYPE name(_NAN_METHOD_ARGS)
                                                      ^
../node_modules/nan/nan.h:263:49: note: expanded from macro '_NAN_METHOD_ARGS'
# define _NAN_METHOD_ARGS _NAN_METHOD_ARGS_TYPE args
                                                ^
../src/connection.cc:163:28: error: no member named 'New' in 'v8::String'; did you mean simply 'New'?
        Handle<String> response = String::New(safeStr);
                                  ^~~~~~~~~~~
                                  New
../src/connection.cc:83:24: note: 'New' declared here
NAN_METHOD(Connection::New)
                       ^
../node_modules/nan/nan.h:1628:50: note: expanded from macro 'NAN_METHOD'
#define NAN_METHOD(name) _NAN_METHOD_RETURN_TYPE name(_NAN_METHOD_ARGS)
                                                 ^
../src/connection.cc:163:40: error: reference to type 'const v8::FunctionCallbackInfo<v8::Value>' could not bind to an lvalue of type 'char *'
        Handle<String> response = String::New(safeStr);
                                              ^~~~~~~
../src/connection.cc:83:1: note: passing argument to parameter 'args' here
NAN_METHOD(Connection::New)
^
../node_modules/nan/nan.h:1628:55: note: expanded from macro 'NAN_METHOD'
#define NAN_METHOD(name) _NAN_METHOD_RETURN_TYPE name(_NAN_METHOD_ARGS)
                                                      ^
../node_modules/nan/nan.h:263:49: note: expanded from macro '_NAN_METHOD_ARGS'
# define _NAN_METHOD_ARGS _NAN_METHOD_ARGS_TYPE args
                                                ^
../src/connection.cc:188:28: error: no member named 'New' in 'v8::String'; did you mean simply 'New'?
        Handle<String> response = String::New(safeStr,safeStr_length);
                                  ^~~~~~~~~~~
                                  New
../src/connection.cc:83:24: note: 'New' declared here
NAN_METHOD(Connection::New)
                       ^
../node_modules/nan/nan.h:1628:50: note: expanded from macro 'NAN_METHOD'
#define NAN_METHOD(name) _NAN_METHOD_RETURN_TYPE name(_NAN_METHOD_ARGS)
                                                 ^
../src/connection.cc:188:48: error: too many arguments to function call, expected single argument 'args', have 2 arguments
        Handle<String> response = String::New(safeStr,safeStr_length);
                                  ~~~~~~~~~~~         ^~~~~~~~~~~~~~
../src/connection.cc:83:1: note: 'New' declared here
NAN_METHOD(Connection::New)
^
../node_modules/nan/nan.h:1628:26: note: expanded from macro 'NAN_METHOD'
#define NAN_METHOD(name) _NAN_METHOD_RETURN_TYPE name(_NAN_METHOD_ARGS)
                         ^
../node_modules/nan/nan.h:264:34: note: expanded from macro '_NAN_METHOD_RETURN_TYPE'
# define _NAN_METHOD_RETURN_TYPE void
                                 ^
../src/connection.cc:212:39: error: too few arguments to function call, single argument 'isolate' was not specified
        Local<Object> response = Object::New();
                                 ~~~~~~~~~~~ ^
/Users/jimmyhmiller/.node-gyp/0.12.0/deps/v8/include/v8.h:2388:3: note: 'New' declared here
  static Local<Object> New(Isolate* isolate);
  ^
../src/connection.cc:214:42: error: no member named 'New' in 'v8::String'; did you mean simply 'New'?
        response->Set(NanNew<String>("status"), String::New(status));
                                                ^~~~~~~~~~~
                                                New
../src/connection.cc:83:24: note: 'New' declared here
NAN_METHOD(Connection::New)
                       ^
../node_modules/nan/nan.h:1628:50: note: expanded from macro 'NAN_METHOD'
#define NAN_METHOD(name) _NAN_METHOD_RETURN_TYPE name(_NAN_METHOD_ARGS)
                                                 ^
../src/connection.cc:214:54: error: reference to type 'const v8::FunctionCallbackInfo<v8::Value>' could not bind to an lvalue of type 'char *'
        response->Set(NanNew<String>("status"), String::New(status));
                                                            ^~~~~~
../src/connection.cc:83:1: note: passing argument to parameter 'args' here
NAN_METHOD(Connection::New)
^
../node_modules/nan/nan.h:1628:55: note: expanded from macro 'NAN_METHOD'
#define NAN_METHOD(name) _NAN_METHOD_RETURN_TYPE name(_NAN_METHOD_ARGS)
                                                      ^
../node_modules/nan/nan.h:263:49: note: expanded from macro '_NAN_METHOD_ARGS'
# define _NAN_METHOD_ARGS _NAN_METHOD_ARGS_TYPE args
                                                ^
../src/connection.cc:217:55: error: no member named 'New' in 'v8::String'; did you mean simply 'New'?
        response->Set(NanNew<String>("errorMessage"), String::New(errorMessage));
                                                      ^~~~~~~~~~~
                                                      New
../src/connection.cc:83:24: note: 'New' declared here
NAN_METHOD(Connection::New)
                       ^
../node_modules/nan/nan.h:1628:50: note: expanded from macro 'NAN_METHOD'
#define NAN_METHOD(name) _NAN_METHOD_RETURN_TYPE name(_NAN_METHOD_ARGS)
                                                 ^
../src/connection.cc:217:67: error: reference to type 'const v8::FunctionCallbackInfo<v8::Value>' could not bind to an lvalue of type 'char *'
        response->Set(NanNew<String>("errorMessage"), String::New(errorMessage));
                                                                  ^~~~~~~~~~~~
../src/connection.cc:83:1: note: passing argument to parameter 'args' here
NAN_METHOD(Connection::New)
^
../node_modules/nan/nan.h:1628:55: note: expanded from macro 'NAN_METHOD'
#define NAN_METHOD(name) _NAN_METHOD_RETURN_TYPE name(_NAN_METHOD_ARGS)
                                                      ^
../node_modules/nan/nan.h:263:49: note: expanded from macro '_NAN_METHOD_ARGS'
# define _NAN_METHOD_ARGS _NAN_METHOD_ARGS_TYPE args
                                                ^
../src/connection.cc:353:15: error: no member named 'Close' in 'v8::HandleScope'
        return scope.Close(response);
               ~~~~~ ^
../src/connection.cc:392:33: error: too few arguments to function call, at least argument 'isolate' must be specified
        Local<Array> rows = Array::New();
                            ~~~~~~~~~~ ^
/Users/jimmyhmiller/.node-gyp/0.12.0/deps/v8/include/v8.h:2417:3: note: 'New' declared here
  static Local<Array> New(Isolate* isolate, int length = 0);
  ^
../src/connection.cc:395:33: error: too few arguments to function call, at least argument 'isolate' must be specified
                Local<Array> row = Array::New();
                                   ~~~~~~~~~~ ^
/Users/jimmyhmiller/.node-gyp/0.12.0/deps/v8/include/v8.h:2417:3: note: 'New' declared here
  static Local<Array> New(Isolate* isolate, int length = 0);
  ^
../src/connection.cc:398:38: error: too few arguments to function call, single argument 'isolate' was not specified
                        Local<Object> field = Object::New();
                                              ~~~~~~~~~~~ ^
/Users/jimmyhmiller/.node-gyp/0.12.0/deps/v8/include/v8.h:2388:3: note: 'New' declared here
  static Local<Object> New(Isolate* isolate);
  ^
../src/connection.cc:401:39: error: no member named 'New' in 'v8::String'; did you mean simply 'New'?
                        field->Set(NanNew<String>("name"), String::New(fieldName));
                                                           ^~~~~~~~~~~
                                                           New
../src/connection.cc:83:24: note: 'New' declared here
NAN_METHOD(Connection::New)
                       ^
../node_modules/nan/nan.h:1628:50: note: expanded from macro 'NAN_METHOD'
#define NAN_METHOD(name) _NAN_METHOD_RETURN_TYPE name(_NAN_METHOD_ARGS)
                                                 ^
../src/connection.cc:401:51: error: reference to type 'const v8::FunctionCallbackInfo<v8::Value>' could not bind to an lvalue of type 'char *'
                        field->Set(NanNew<String>("name"), String::New(fieldName));
                                                                       ^~~~~~~~~
../src/connection.cc:83:1: note: passing argument to parameter 'args' here
NAN_METHOD(Connection::New)
^
../node_modules/nan/nan.h:1628:55: note: expanded from macro 'NAN_METHOD'
#define NAN_METHOD(name) _NAN_METHOD_RETURN_TYPE name(_NAN_METHOD_ARGS)
                                                      ^
../node_modules/nan/nan.h:263:49: note: expanded from macro '_NAN_METHOD_ARGS'
# define _NAN_METHOD_ARGS _NAN_METHOD_ARGS_TYPE args
                                                ^
../src/connection.cc:405:39: error: too few arguments to function call, expected 2, have 1; did you mean '::Connection::New'?
                        field->Set(NanNew<String>("type"), Integer::New(fieldType));
                                                           ^~~~~~~~~~~~
                                                           ::Connection::New
../src/connection.cc:83:24: note: '::Connection::New' declared here
NAN_METHOD(Connection::New)
                       ^
../node_modules/nan/nan.h:1628:50: note: expanded from macro 'NAN_METHOD'
#define NAN_METHOD(name) _NAN_METHOD_RETURN_TYPE name(_NAN_METHOD_ARGS)
                                                 ^
../src/connection.cc:409:41: error: no matching function for call to 'Null'
                                field->Set(NanNew<String>("value"), Null());
                                                                    ^~~~
/Users/jimmyhmiller/.node-gyp/0.12.0/deps/v8/include/v8.h:306:28: note: candidate function not viable: requires single argument 'isolate', but no arguments
      were provided
  friend Handle<Primitive> Null(Isolate* isolate);
                           ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
make: *** [Release/obj.target/pgsync/src/connection.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1067:12)
gyp ERR! System Darwin 14.1.0
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/pg-sync
gyp ERR! node -v v0.12.0
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok 
pg-sync@0.1.3 /usr/local/lib/node_modules/pg-sync
└── nan@1.2.0

**Comment by RayKitajima** [comment]
Hi jimmyhmiller.
I just committed and published new version(0.2.0) to npm, with support for node 0.12.
Thanks for your report.
